apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: gcr.io/bedrock/bedrock-services-web
          imagePullPolicy: Always
          name: main
          env:
            - name: NODE_ENV
              value: "production"
            - name: DOMAIN
              value: bedrock.co.uk
            - name: API_URL
              value: "https://api.bedrock.co.uk"
          ports:
            - name: http-server
              containerPort: 2200
